<?php
// +---------------------------------------------------------------------------+
// | This file is part of the Openology FrameWork                              |
// | Copyright (c) 2004 Openology Pte Ltd                                      |
// |                                                                           |
// | For the full copyright and license information, please view the COPYRIGHT |
// | file that was distributed with this source code. If the COPYRIGHT file is |
// | missing, please visit Openology homepage: http://www.openology.org/       |
// +---------------------------------------------------------------------------+ 
//
// $Id$ 

/**
 * Implements a drop-down select of countries.
 *
 * @package openology
 * @subpackage form.elements
 * @author Ken Chew <ken.chew@openology.com>
 * @copyright (c) 2004-2005 Openology Pte Ltd
 */
include_once OOO_CORE.'/form/elements/FormSelect.php';
/**
 * Implements a drop-down select of countries.
 *
 * @package openology.form.elements
 */

class FormSelectCountry extends FormSelect
{     
    /**
     * Constructor
     * 
     * @return  void
     */
    function FormSelectCountry()
    {
        parent::FormSelect();          

        $countries = array(    
            'AF'=>'Afghanistan',
            'AL'=>'Albania',
            'DZ'=>'Algeria',
            'AS'=>'American Samoa',
            'AD'=>'Andorra',
            'AO'=>'Angola',
            'AI'=>'Anguilla',
            'AQ'=>'Antarctica',
            'AG'=>'Antigua and Barbuda',
            'AR'=>'Argentina',
            'AM'=>'Armenia',
            'AW'=>'Aruba',
            'AU'=>'Australia',
            'AT'=>'Austria',
            'AZ'=>'Azerbaijan',
            'BS'=>'Bahamas',
            'BH'=>'Bahrain',
            'BD'=>'Bangladesh',
            'BB'=>'Barbados',
            'BY'=>'Belarus',
            'BE'=>'Belgium',
            'BZ'=>'Belize',
            'BJ'=>'Benin',
            'BM'=>'Bermuda',
            'BT'=>'Bhutan',
            'BO'=>'Bolivia',
            'BA'=>'Bosnia and Herzegovina',
            'BW'=>'Botswana',
            'BV'=>'Bouvet Island',
            'BR'=>'Brazil',
            'IO'=>'British Indian Ocean Territory',
            'BN'=>'Brunei',
            'BG'=>'Bulgaria',
            'BF'=>'Burkina Faso',
            'BI'=>'Burundi',
            'KH'=>'Cambodia',
            'CM'=>'Cameroon',
            'CA'=>'Canada',
            'CV'=>'Cape Verde',
            'KY'=>'Cayman Islands',
            'CF'=>'Central African Republic',
            'TD'=>'Chad',
            'CL'=>'Chile',
            'CN'=>'China',
            'CX'=>'Christmas Island',
            'CC'=>'Cocos &#40;Keeling&#41; Islands',
            'CO'=>'Colombia',
            'KM'=>'Comoros',
            'CG'=>'Congo',
            'CK'=>'Cook Islands',
            'CR'=>'Costa Rica',
            'CI'=>'C&#244;te d&#39;Ivoire',
            'HR'=>'Croatia &#40;Hrvatska&#41;',
            'CU'=>'Cuba',
            'CY'=>'Cyprus',
            'CZ'=>'Czech Republic',
            'CD'=>'Congo &#40;DRC&#41;',
            'DK'=>'Denmark',
            'DJ'=>'Djibouti',
            'DM'=>'Dominica',
            'DO'=>'Dominican Republic',
            'TP'=>'East Timor',
            'EC'=>'Ecuador',
            'EG'=>'Egypt',
            'SV'=>'El Salvador',
            'GQ'=>'Equatorial Guinea',
            'ER'=>'Eritrea',
            'EE'=>'Estonia',
            'ET'=>'Ethiopia',
            'FK'=>'Falkland Islands &#40;Islas Malvinas&#41;',
            'FO'=>'Faroe Islands',
            'FJ'=>'Fiji Islands',
            'FI'=>'Finland',
            'FR'=>'France',
            'GF'=>'French Guiana',
            'PF'=>'French Polynesia',
            'TF'=>'French Southern and Antarctic Lands',
            'GA'=>'Gabon',
            'GM'=>'Gambia',
            'GE'=>'Georgia',
            'DE'=>'Germany',
            'GH'=>'Ghana',
            'GI'=>'Gibraltar',
            'GR'=>'Greece',
            'GL'=>'Greenland',
            'GD'=>'Grenada',
            'GP'=>'Guadeloupe',
            'GU'=>'Guam',
            'GT'=>'Guatemala',
            'GN'=>'Guinea',
            'GW'=>'Guinea-Bissau',
            'GY'=>'Guyana',
            'HT'=>'Haiti',
            'HM'=>'Heard Island and McDonald Islands',
            'HN'=>'Honduras',
            'HK'=>'Hong Kong SAR',
            'HU'=>'Hungary',
            'IS'=>'Iceland',
            'IN'=>'India',
            'ID'=>'Indonesia',
            'IR'=>'Iran',
            'IQ'=>'Iraq',
            'IE'=>'Ireland',
            'IL'=>'Israel',
            'IT'=>'Italy',
            'JM'=>'Jamaica',
            'JP'=>'Japan',
            'JO'=>'Jordan',
            'KZ'=>'Kazakhstan',
            'KE'=>'Kenya',
            'KI'=>'Kiribati',
            'KR'=>'Korea',
            'KW'=>'Kuwait',
            'KG'=>'Kyrgyzstan',
            'LA'=>'Laos',
            'LV'=>'Latvia',
            'LB'=>'Lebanon',
            'LS'=>'Lesotho',
            'LR'=>'Liberia',
            'LY'=>'Libya',
            'LI'=>'Liechtenstein',
            'LT'=>'Lithuania',
            'LU'=>'Luxembourg',
            'MO'=>'Macao SAR',
            'MK'=>'Macedonia, Former Yugoslav Republic of',
            'MG'=>'Madagascar',
            'MW'=>'Malawi',
            'MY'=>'Malaysia',
            'MV'=>'Maldives',
            'ML'=>'Mali',
            'MT'=>'Malta',
            'MH'=>'Marshall Islands',
            'MQ'=>'Martinique',
            'MR'=>'Mauritania',
            'MU'=>'Mauritius',
            'YT'=>'Mayotte',
            'MX'=>'Mexico',
            'FM'=>'Micronesia',
            'MD'=>'Moldova',
            'MC'=>'Monaco',
            'MN'=>'Mongolia',
            'MS'=>'Montserrat',
            'MA'=>'Morocco',
            'MZ'=>'Mozambique',
            'MM'=>'Myanmar',
            'NA'=>'Namibia',
            'NR'=>'Nauru',
            'NP'=>'Nepal',
            'NL'=>'Netherlands',
            'AN'=>'Netherlands Antilles',
            'NC'=>'New Caledonia',
            'NZ'=>'New Zealand',
            'NI'=>'Nicaragua',
            'NE'=>'Niger',
            'NG'=>'Nigeria',
            'NU'=>'Niue',
            'NF'=>'Norfolk Island',
            'KP'=>'North Korea',
            'MP'=>'Northern Mariana Islands',
            'NO'=>'Norway',
            'OM'=>'Oman',
            'PK'=>'Pakistan',
            'PW'=>'Palau',
            'PA'=>'Panama',
            'PG'=>'Papua New Guinea',
            'PY'=>'Paraguay',
            'PE'=>'Peru',
            'PH'=>'Philippines',
            'PN'=>'Pitcairn Islands',
            'PL'=>'Poland',
            'PT'=>'Portugal',
            'PR'=>'Puerto Rico',
            'QA'=>'Qatar',
            'RE'=>'Reunion',
            'RO'=>'Romania',
            'RU'=>'Russia',
            'RW'=>'Rwanda',
            'WS'=>'Samoa',
            'SM'=>'San Marino',
            'ST'=>'S&#227;o Tom&#233; and Pr&#237;ncipe',
            'SA'=>'Saudi Arabia',
            'SN'=>'Senegal',
            'YU'=>'Serbia and Montenegro',
            'SC'=>'Seychelles',
            'SL'=>'Sierra Leone',
            'SG'=>'Singapore',
            'SK'=>'Slovakia',
            'SI'=>'Slovenia',
            'SB'=>'Solomon Islands',
            'SO'=>'Somalia',
            'ZA'=>'South Africa',
            'GS'=>'South Georgia and the South Sandwich Islands',
            'ES'=>'Spain',
            'LK'=>'Sri Lanka',
            'SH'=>'St. Helena',
            'KN'=>'St. Kitts and Nevis',
            'LC'=>'St. Lucia',
            'PM'=>'St. Pierre and Miquelon',
            'VC'=>'St. Vincent and the Grenadines',
            'SD'=>'Sudan',
            'SR'=>'Suriname',
            'SJ'=>'Svalbard and Jan Mayen',
            'SZ'=>'Swaziland',
            'SE'=>'Sweden',
            'CH'=>'Switzerland',
            'SY'=>'Syria',
            'TW'=>'Taiwan',
            'TJ'=>'Tajikistan',
            'TZ'=>'Tanzania',
            'TH'=>'Thailand',
            'TG'=>'Togo',
            'TK'=>'Tokelau',
            'TO'=>'Tonga',
            'TT'=>'Trinidad and Tobago',
            'TN'=>'Tunisia',
            'TR'=>'Turkey',
            'TM'=>'Turkmenistan',
            'TC'=>'Turks and Caicos Islands',
            'TV'=>'Tuvalu',
            'UG'=>'Uganda',
            'UA'=>'Ukraine',
            'AE'=>'United Arab Emirates',
            'UK'=>'United Kingdom',
            'US'=>'United States',
            'UM'=>'United States Minor Outlying Islands',
            'UY'=>'Uruguay',
            'UZ'=>'Uzbekistan',
            'VU'=>'Vanuatu',
            'VA'=>'Vatican City',
            'VE'=>'Venezuela',
            'VN'=>'Viet Nam',
            'VG'=>'Virgin Islands &#40;British&#41;',
            'VI'=>'Virgin Islands',
            'WF'=>'Wallis and Futuna',
            'YE'=>'Yemen',
            'ZM'=>'Zambia',
            'ZW'=>'Zimbabwe'
            );
    
        $this->setAttribute('option', $countries);
    }
}
?>
